# https://financialmodelingprep.com/api/v3/stock/list
symbol_list_types = ['stock', 'etf', 'fund', 'trust']

# 'None' is for symbols that don't have an exchange
exchange_dict = {
  'None': 'None',
  'SET': 'Thailand',
  'BUD': 'Budapest',
  'MIL': 'Milan',
  'HAM': 'Hamburg',
  'LSE': 'London Stock Exchange',
  'PRA': 'Prague',
  'SAO': 'São Paulo',
  'OSL': 'Oslo Stock Exchange',
  'CPH': 'Copenhagen',
  'NEO': 'NEO',
  'XETRA': 'Frankfurt Stock Exchange',
  'MCX': 'Moscow Stock Exchange',
  'DFM': 'Dubai',
  'OTC': 'Other OTC',
  'DUS': 'Dusseldorf',
  'BVC': 'BVC',
  'VIE': 'Vienna',
  'KUW': 'Kuwait',
  'SHH': 'Shanghai',
  'HEL': 'Helsinki',
  'PNK': 'Other OTC',
  'HOSE': 'Ho Chi Minh Stock Exchange',
  'SGO': 'Santiago',
  'JPX': 'Tokyo',
  'AMS': 'Amsterdam',
  'ASX': 'Australian Securities Exchange',
  'ATH': 'Athens',
  'NASDAQ': 'NASDAQ',
  'TSXV': 'Toronto Stock Exchange Ventures',
  'NYSE': 'New York Stock Exchange',
  'EGX': 'EGX',
  'ICE': 'Iceland',
  'RIS': 'Riga',
  'CNQ': 'Canadian Securities Exchange',
  'STU': 'Stuttgart',
  'EURONEXT': 'Paris',
  'IST': 'Istanbul Stock Exchange',
  'SIX': 'Swiss Exchange',
  'DXE': 'Cboe Europe',
  'STO': 'Stockholm Stock Exchange',
  'IOB': 'International Order Book',
  'BRU': 'Paris',
  'HKSE': 'HKSE',
  'WSE': 'Warsaw Stock Exchange',
  'BSE': 'Bombay Stock Exchange',
  'CAI': 'EGX',
  'MUN': 'Munich',
  'SAU': 'Saudi',
  'SHZ': 'Shenzhen',
  'BME': 'Madrid Stock Exchange',
  'TWO': 'Taipei Exchange',
  'KOE': 'KOSDAQ',
  'JNB': 'Johannesburg',
  'SES': 'Stock Exchange of Singapore',
  'TAI': 'Taiwan',
  'TSX': 'Toronto Stock Exchange',
  'BER': 'Berlin',
  'KLS': 'Kuala Lumpur',
  'KSC': 'KSE',
  'NSE': 'National Stock Exchange of India',
  'MEX': 'Mexico',
  'AQS': 'Aquis AQSE',
  'TLV': 'Tel Aviv',
  'NZE': 'NZSE',
  'BUE': 'Buenos Aires',
  'JKT': 'Jakarta Stock Exchange',
  'AMEX': 'New York Stock Exchange Arca',
  'DOH': 'Qatar',
  'CBOE': 'Cboe US'
}